### PR TITLE
Feature/eval canvas by reg

### PR DESCRIPTION
**Pull request by winterrk**
# Critical Changes
Canvas Lookups via Middleware Added
Middleware lookups standardized (404 = null result, error handling)

# Changes
Standardized variable names in AuraEnabled functions

# Issues Closed

### CODE REVIEW

**Comment by winterrk** [comment]
With this version I'd like to do a short demo w/ you guys. I've added a bunch of webhooking out to the middleware via less confusion / more single button clicks.

**Comment by Jordan-OEE** [comment]
[like]  Schroeder,Jordan reacted to your message:
________________________________

**Comment by Jordan-OEE** [comment]
Thanks Kyle, that would be great!

Want to find some to find some time on our calendars next week for a demo session?  We could bring Garet, Chris, and Rob in as they all have some form of involvement with the changes.

Best,
Jordan

**Review by gtucker25 — APPROVED** [review]

**Comment by winterrk** [comment]
Merging & building a beta - will put some time on the calendar.

**Pull request merged**
